name: deploy myblog

on:
    push:  # 当main分支被push，以及paths里面定义的被改变时，触发xxx命令
        branches: 
            - 'main' #push操作时，对应的分支
        paths: 
            - '.github/workflows/*' #  什么文件或者文件夹里的文件变动时，触发
            - 'src/*'
            - 'package.json'
            - 'vite.config.js'
            
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        timeout-minutes: 15

        steps:
            - uses: actions/checkout@v4 #使用哪一个已经好了的action，除了这个action之外，还有其他功能的action

            - name: 设置Node.js环境
              uses: actions/setup-node@v4
              with:
                node-version: '18'
                cache: 'npm'

            - name: 安装依赖开始
              run: npm install

            - name: 开始构建
              run: npm run build

            - name: 设置SSH--开始
              uses: webfactory/ssh-agent@v0.8.0
              with:
                ssh-private-key: ${{ secrets.ALIYUN_ESC_SECRET }}

            - name: 部署到服务器--开始
              run: |
                echo "开始部署..."
                # 压缩 dist 目录
                tar -czf dist.tar.gz dist/
                
                # 使用 scp 传输文件到服务器
                scp -o StrictHostKeyChecking=no dist.tar.gz root@8.134.205.132:/project/blogs/dist/
                
                # 在服务器上解压文件
                ssh -o StrictHostKeyChecking=no root@8.134.205.132 '
                  cd /project/blogs/dist &&
                  rm -rf dist &&
                  tar -xzf dist.tar.gz &&
                  rm dist.tar.gz
                ' || {
                    echo "部署失败，错误代码: $?"
                    exit 1
                }

